[project]
name = "python-variables"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yahyazoom17", email = "yahyafreelance1727@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
python-variables = "python_variables:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
