[project]
name = "tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yahya", email = "yahyafreelance1727@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
]

[project.scripts]
tutorials = "tutorials:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
